- name: Make sure we have a 'wheel' group
  group:
    name: wheel
    state: present
  become: true

- name: Allow 'wheel' group to have passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%wheel'
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'
  become: true

- block:
  - name: Add sudoers users to wheel group
    user:
      name: "{{ item.user_name }}"
      groups: wheel
      append: yes
      state: "{{ item.state }}"
      createhome: yes
    become: true
    with_items: "{{ secrets.users | default([]) }}"

  - name: Set up authorized keys for the sudors
    authorized_key:
      user: "{{ item.user_name }}"
      key:  "{{ item.public_key }}"
    when: item.public_key is defined
    become: true
    with_items: "{{ secrets.users | default([]) }}"

  when: secrets.users is defined

- block:
  - name: Make sure we have an app group
    group:
      name: app
      state: present
    become: true

  - name: Create app user
    user:
      name: app
      groups: app
      append: yes
      state: present
      home: /srv/app
    become: true

