- name: Install PHP7fpm packages
  apt:
    name: "{{ item }}"
    state: latest
  become: true
  with_items: "{{ global_data.packages.php_packages | default('php7.0-fpm') }}"

  - name: Update php.ini
    copy:
      src: "./files/php.ini.tmpl"
      dest: "/etc/php/7.0/fpm/php.ini"
      owner: root
      group: root
      mode: 644
      backup: yes
    become: true

  - name: Update php-fpm.conf
    copy:
      src: "./files/php-fpm.conf.tmpl"
      dest: "/etc/php/7.0/fpm/php-fpm.conf"
      owner: root
      group: root
      mode: 644
      backup: yes
    become: true

  - name: Update www.conf
    copy:
      src: "./files/www.conf.tmpl"
      dest: "/etc/php/7.0/fpm/pool.d/www.conf"
      owner: root
      group: root
      mode: 644
      backup: yes
    become: true

  - name: Reload php-fpm
    service:
      name: php7.0-fpm
      state: reloaded
    become: true