#get some data from the shared vpc
- name:  Get vpc data for stack
  ec2_vpc_net_facts:
    filters:
      'tag:Name': "{{ [vpc_name, global_data.domain_name]|join('.') }}"
  register: vpc_data
  always_run: true
  tags:
    - always

- name: Get list of subnets
  ec2_vpc_subnet_facts:
    filters:
      vpc-id: "{{ vpc_data.vpcs.0.id }}"
  register: subnet_data
  always_run: true
  tags:
    - always

- name: Get account id data
  shell: aws iam list-users | grep Arn | cut -d ':' -f 6 | uniq
  register: account_id
  always_run: true
  tags:
    - always

- name: Make accountid value available
  set_fact:
    aws_acc_id: "{{ account_id.stdout }}"
  always_run: true
  tags:
    - always

- name: Setup vars for playbook
  set_fact:
    private_subnets: "{{ subnet_data.subnets | selectattr('tags.Name', 'match', '^private.*')| map(attribute='id') | list }}"
    public_subnets: "{{ subnet_data.subnets | selectattr('tags.Name', 'match', '^public.*')| map(attribute='id') | list }}"
    vpc_id: "{{ vpc_data.vpcs.0.id }}"
  always_run: true
  tags:
    - always


- name: Create infrastructure
  include: create.main.yml
  when: destroy_stack is undefined or not destroy_stack

- name: Destroy infrastructure
  include: destroy.main.yml
  when: destroy_stack is defined and destroy_stack